### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by christian-ortmann** [INFO523-S24/project-01-Weather-Gurus#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

Christian Ortmann - @christian-ortmann

Roxana Akbarsharifi - @rxnsh

Shashank Yadav - @xinformatics

Abhishek kumar - @Abhi291712

Gorantla Sai Laasya - @Sailaasya-1

Divya Liladhar Dhole - @Divyadhole

- Describe the goal of the project.
To understand weather patterns and trends based on the location 

- Describe the data used or collected.
Collected by NASA from 1951-1980 recording land, sea, air surface.

- Describe the goal of the project.
To understand weather patterns and trends based on the location 

- Describe the data used or collected.
Collected by NASA from 1951-1980 recording land, sea, and air surface.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Using statistical methods such as time series, trend, and comparative analysis. They plan to isolate time and seasonal temperature data and import external temperature data.

- Is there anything that is unclear from the proposal?
How are the locations defined in the hemisphere data?. What is the resolution of the location data, how minute do they expect their result to be. How do they define erratic behavior in Question 2?

- Provide constructive feedback on how the team might be able to improve their project.
Import data that can break down each hemisphere to a smaller scale into smaller quadrants. Potentially add in elevation data for land surface data.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

Relating to weather trends such as El Nino and La Nina or human induced trends such as Climate Change. Also how does the rate of change of temperature change over time, acceleration or deceleration?

- Provide constructive feedback on any issues with file and/or code organization.
Github logo does not link to the Repo for this team. Data organization is very strong. Missing spaces after ## for Q2 to have it render correctly

**Comment by d-koudz** [comment]
-To understand weather patterns and trends based on the location
The data mainly tracks trends in weather and global warming. The introduction was changed to reflect that. Thank you for pointing out this issue.

-Collected by NASA from 1951-1980 recording land, sea, and air surface.
The data actually extends till half of 2023. The introduction was changed to reflect that. Thank you for pointing out this issue.


-How are the locations defined in the hemisphere data?. What is the resolution of the location data, how minute do they expect their result to be. How do they define erratic behavior in Question 2?

Research questions were revised to fix this confusion. 

- Github logo does not link to the Repo for this team. Data organization is very strong. Missing spaces after ## for Q2 to have it render correctly
rendering issues were fixed. Thank you for pointing that out.
