### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by mellica97** [INFO523-S24/project-01-Weather-Gurus#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- [Melika Sharifi] - @[mellica97]
- [Rajitha Reddy Tiruthani] - @[RAJITHAREDDYTIRUTHANI]
- [Gowtham Gopalakrishnan] - @[Gowtham-18]
- [Maksim Kulik] - [@h-akston]
- Toluwanimi Olorunnisola - @ToluGb
- Surya Vardhan Dama - @suryavardhandama

- Describe the goal of the project.
The goal of the project is to understand past and present climate trends and potentially predict future patterns.
The dataset contains four CSV files, providing temperature anomalies across different spatial and temporal scales for a long period from 1880 to 2022.

- Describe the data used or collected.
Dataset: land-surface, sea surface, air temperature anomalies.
Variables Involved: Yearly Temperature Anomalies, Seasonal Temperature Anomalies
Variables to be Created: 2023 Temperature Anomalies, Seasonal Anomalies for 2023

- Describe how the research question will be answered, e.g. what approaches/methods will be used.
Preparation of Data: It is proposed that the additional data for the year 2023 will be sourced from NASA's GISS Surface Temperature Analysis to complete the dataset. Variables such as seasonal anomalies for 2023 will be calculated accordingly.
For the first research question, zonal annual temperature anomalies will be analyzed by transforming the data to a long format and visualizing trends using time series plots and heatmaps.
For the second research question, seasonal temperature anomalies will be examined by comparing patterns across hemispheres using time series plots, box plots, and histograms.
Statistical methods: These include time series analysis to compare temperature anomalies against historical records, trend analysis using linear regression, and comparative analysis to evaluate temperature trends across different periods.

- Is there anything unclear from the proposal?
The process of transforming data from a wide format to a long format could be more explicitly explained, especially for readers unfamiliar with data structuring concepts. 
The proposal does not specify how you plan to assess or handle data quality issues, missing data, or outliers. A brief mention of the techniques for dealing with these issues.
The proposal mentions analyzing both seasonal and monthly temperature anomalies but does not clearly distinguish between these two approaches in the analysis plan.

- Provide constructive feedback on how the team might be able to improve their project.
Consider the potential impact of missing or incomplete data on the analysis, particularly when sourcing the 2023 temperature anomaly data from external sources.
Conduct a thorough data quality and uncertainty analysis. Assess the reliability of the datasets by examining potential biases, errors, or gaps in the data collection methods used by NASA. Address how these factors might influence the analysis results and conclusions.
Explore the use of machine learning models to predict future temperature anomalies based on historical data.
Implement anomaly detection algorithms to identify years or seasons that significantly deviate from expected temperature patterns.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation?
We are particularly interested in the comparative analysis of seasonal temperature anomalies between the Northern and Southern Hemispheres. Highlighting the key differences and similarities in temperature trends across different seasons and hemispheres, and the season with more erratic behavior would provide valuable insights into global climate patterns.
In the presentation, we would like to see a detailed examination of the seasonal temperature anomalies, with a focus on identifying any notable trends, fluctuations, or anomalies observed in both hemispheres over time.
Highlighting key findings or insights from the comparative analysis, such as upward/downward trends, which seasons or months exhibit more erratic behavior, or significant temperature changes, would be beneficial for everyone's understanding.

- Provide constructive feedback on any issues with file and/or code organization.
There are no issues with code organization.

- (Optional) Any further comments or feedback?
Plan for Scalability: Consider how your project might be scaled or extended in the future, For instance, could the methodologies you develop be applied to other climate-related datasets or used to track other environmental indicators?

**Comment by d-koudz** [comment]
Thank you for pointing these issues out: 
Two points here have the same answer:


-Conduct a thorough data quality and uncertainty analysis. Assess the reliability of the datasets by examining potential biases, errors, or gaps in the data collection methods used by NASA. Address how these factors might influence the analysis results and conclusions.

- The proposal does not specify how you plan to assess or handle data quality issues, missing data, or outliers. A brief mention of the techniques for dealing with these issues.


NASA has, and still is doing a great job regarding the quality control of this specific dataset. You can read more about how they historically have been handling the issue of quality control  in this research paper: https://pubs.giss.nasa.gov/docs/1999/1999_Hansen_ha03200f.pdf

-The proposal mentions analyzing both seasonal and monthly temperature anomalies but does not clearly distinguish between these two approaches in the analysis plan.
The dataset already has ready columns dedicated to months and others to seasons. The research questions will be changed to reflect that.


- Consider the potential impact of missing or incomplete data on the analysis, particularly when sourcing the 2023 temperature anomaly data from external sources.
The data is being resourced from its original source which is NASA. 

Again thank you for your great feedback.
