### ISSUE TITLE
Proposal Regrade

### ISSUE THREAD

**Issue by zandi-omid** [INFO523-S24/project-01-Weather-Gurus#4]
Hi Greg,
I am writing for a regrade to the proposal. We added the description to the dataset and loaded the dataset as well.
Thank You,
Omid

**Comment by Gchism94** [comment]
I looked at your proposal again. Some of your analysis plan is a little wordy, but you did a good job. Your second score is **10/10**, so your new score is **9.5/10**

**Comment by zandi-omid** [comment]
Thx.
