### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by rxnsh** [INFO523-S24/project-01-Weather-Gurus#5]
The following is the peer review of the Presentation proposal by Tech Titans. The team members that participated in this review are
- Christian Ortmann 
[@christian ortmann](https://datamineaz-spring2024.slack.com/team/U06DDUZA21J)

- Abhishek Kumar @Abhi291712
- Divya Liladhar Dhole @Divyadhole
- Roxana Akbarsharifi @rxnsh
- Gorantla Sai Laasya @Sailaasya-1
- Shashank Yadav @xinformatics
- Content: Is the research question well designed and is the data being used relevant to the research question?
the research question on temperature anomalies was clear and relevant, and the data used was spot-on for what you were aiming to uncover.
- Content: Did the team use appropriate visualizations and did they interpret them accurately?
The visuals, especially ridge plots and heat maps made the complex info much easier to grasp.
- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The team’s creativity was particularly evident in the way complex data was distilled into clear, engaging visuals.
- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides were clean and easy to read, and the graphics were a nice touch. Everything flowed together seamlessly, telling a clear story from start to finish.
- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
They delivered everything confidently and cohesively during the presentation.

**Comment by remisublette** [comment]
Thanks for your feedback!
