### ISSUE TITLE
Presentation peer review by Season's Screenings

### ISSUE THREAD

**Issue by Gowtham-18** [INFO523-S24/project-01-Weather-Gurus#6]
The following is the peer review of the Presentation proposal by Season's Screeenings. The team members that participated in this review are 

- Melika Akbarsharifi - @mellica97
- Surya Vardhan Dama - @suryavardhandama
- Toluwanimi Olorunnisola - @ToluGb
- Rajitha Reddy Tiruthani -@RAJITHAREDDYTIRUTHANI
- Maksim Kulik - @h-akston
- Gowtham Gopalakrishnan - @Gowtham-18

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research question is well-designed, focusing on analyzing global and hemispheric temperature anomalies across different temporal and spatial scales. The data used is highly relevant, spanning a long period from 1880 to 2022 and covering various geographic regions.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes,  The team appropriately used visualizations such as heatmaps, ridge plots, time series analysis, and box plots to represent the data. They accurately interpreted these visualizations to draw insights into global and hemispheric temperature trends, enhancing the audience's understanding.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The project demonstrates careful consideration of limitations, emphasizing the interdisciplinary nature of addressing climate change challenges. The team's thorough planning and implementation are evident through the selection of appropriate methods and visualizations.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well-organized, featuring concise text, readable fonts, and clear figures with legible labels and legends. The visuals effectively complement the verbal presentation, facilitating comprehension without overwhelming the audience with excessive information.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team presents professionally, showing confidence and competence in their delivery. They appear well-practiced, not relying heavily on scripts, and each team member contributes meaningfully to the discussion, showcasing a collaborative effort. the project showcases a commendable level of professionalism, thoroughness in analysis, and effective communication of findings through well-designed visualizations and presentations.

**Comment by remisublette** [comment]
Thanks for your feedback!
